### ISSUE TITLE
Display alerts consistently across the site

### ISSUE THREAD

**Issue by ttmp** [postcode/senoia#172]
Some of these seem to be on the main page, some only on the All Plans page. We should decide which alerts show up where.

**Comment by villesundberg** [comment]
The main page currently notifies about collaboration invitations. All other alerts are on the All Plans page.

Are there any alerts that we would want to show on the main page instead of the All Plans page? @ttmp: any user insight on this?

One possible way would be to include a notification counter on the main page, and have the All Plans page serve as the notification hub.

Another option is to create a separate page just for notifications, and include a notification counter on the top bar.

I think the last option might be the most future-proof and where we may want to go eventually, but do we want to hold off on until after this release?
