### ISSUE TITLE
Make assets editable through the modal

### ISSUE THREAD

**Issue by ttmp** [postcode/senoia#206]
I'm not sure that assets need to be editable on the main page. Data entry for new assets happens in a modal, so it probably make sense that if you want to edit an asset you also click on an edit icon (like with collaborators), which would pull up the original modal with current info saved.

Not a top priority, but this could also help with #205.

**Comment by hampelm** [comment]
Provider list is created using https://harvesthq.github.io/chosen/options.html

**Comment by hampelm** [comment]
@andyhull The `update` method of the `first_aid_stations_controller` has a section for Communications, though those are no longer in the form. The operational period form has also has a line under Communications that reads "All event safety personnel will have a list of contact info and will be communicating as specified in the Medical Assets section". 

Are those still supposed to be included? If yes can you share more details on the spec? I found the old PR where you added them, not sure what changed since then.

**Comment by hampelm** [comment]
Closed in #346.
